import { Capacitor } from '@capacitor/core'
import { APP_CONFIG } from './config'
let n=false,w=false
async function native(userId){try{const{default:O}=await import('@onesignal/capacitor-plugin');if(!n){await O.initialize(APP_CONFIG.oneSignalAppId);n=true}if(userId){await O.login(userId);await O.User.setLanguage('ar')}return true}catch(e){console.warn(e);return false}}
function sdk(){return new Promise((resolve,reject)=>{if(document.querySelector('script[data-onesignal-sdk]'))return resolve();const s=document.createElement('script');s.src='https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js';s.defer=true;s.dataset.onesignalSdk='1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function web(userId){try{await sdk();window.OneSignalDeferred=window.OneSignalDeferred||[];return await new Promise(resolve=>window.OneSignalDeferred.push(async O=>{try{if(!w){await O.init({appId:APP_CONFIG.oneSignalAppId,allowLocalhostAsSecureOrigin:true,serviceWorkerPath:'OneSignalSDKWorker.js',serviceWorkerParam:{scope:'./'},notifyButton:{enable:false}});w=true}if(userId)await O.login(userId);resolve(true)}catch(e){console.warn(e);resolve(false)}}))}catch{return false}}
export async function initNotifications(userId){return Capacitor.isNativePlatform()?native(userId):web(userId)}
export async function requestNotificationPermission(){try{if(Capacitor.isNativePlatform()){const{default:O}=await import('@onesignal/capacitor-plugin');return await O.Notifications.requestPermission(true)}window.OneSignalDeferred=window.OneSignalDeferred||[];return await new Promise(resolve=>window.OneSignalDeferred.push(async O=>{try{resolve(await O.Notifications.requestPermission())}catch{resolve(false)}}))}catch{return false}}
export async function logoutNotifications(){try{if(Capacitor.isNativePlatform()){const{default:O}=await import('@onesignal/capacitor-plugin');await O.logout();return}window.OneSignalDeferred=window.OneSignalDeferred||[];window.OneSignalDeferred.push(async O=>{try{await O.logout()}catch{}})}catch{}}
